services:
  postgres:
    image: 'postgres:latest'
    container_name: "PostgresDB"
    ports:
      - '7108:5432'
    environment:
      - 'POSTGRES_DB=PostgresDB'
      - 'POSTGRES_USER=HaiDang91'
      - 'POSTGRES_PASSWORD=9107'
    volumes:
      - ./src/main/resources/postgresSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql