package org.example.server.network;

import org.example.model.enums.MessageType;
import org.example.model.user.User;
import org.example.payload.ErrorDetail;
import org.example.payload.Request;
import org.example.payload.Response;
import org.example.server.exception.BaseAppException;
import org.example.server.network.command.Command;
import org.example.server.network.command.CommandRegistry;
import org.example.util.FileLogger;
import org.example.util.JsonConverter;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.SocketChannel;
import java.nio.charset.StandardCharsets;

/**
 * SOLID: Single Responsibility - Handles network request processing and command execution.
 */
public class CommandHandler implements Runnable {
    private final SocketChannel clientChannel;
    private final String clientAddress; // Cache for logging
    private final String message;
    private final CommandRegistry commandRegistry;
    private final org.example.server.service.user.auth.AuthService authService;

    /**
     * Constructs a CommandHandler for a specific client and message.
     * @param clientChannel the client's socket channel
     * @param message the received message string
     * @param commandRegistry the registry for looking up commands
     * @param authService the service for handling authentication and authorization
     */
    public CommandHandler(SocketChannel clientChannel, String message, CommandRegistry commandRegistry, org.example.server.service.user.auth.AuthService authService) {
        this.clientChannel = clientChannel;
        this.message = message;
        this.commandRegistry = commandRegistry;
        this.authService = authService;
        
        String addr = "Unknown";
        try {
            addr = clientChannel.getRemoteAddress().toString();
        } catch (IOException ex) {
            FileLogger.debug("Failed to get remote address: " + ex.getMessage());
        }
        this.clientAddress = addr;
    }

    /**
     * Executes the command in a separate thread.
     */
    @Override
    public void run() {
        try {
            // Log incoming raw message
            FileLogger.info(">>> INCOMING from " + clientAddress + ": " + message);

            // Heartbeat: Update every time a client sends a valid message
            HeartbeatRegistry.update(clientChannel);

            Request request = JsonConverter.fromJson(message, Request.class);
            if (request == null) return;
            
            Response<?> response = handleRequest(request);
            sendResponse(response);
            
        } catch (BaseAppException e) {
            FileLogger.warn("Application error handling command from " + clientAddress + ": " + e.getMessage() + " [" + e.getErrorCode() + "]");
            sendResponse(new Response<>(MessageType.ERROR, false, e.getMessage(), new ErrorDetail(e.getErrorCode(), e.getMessage())));
        } catch (Exception e) {
            FileLogger.error("Critical error handling command from " + clientAddress + ": " + JsonConverter.maskSensitiveData(message), e);
            sendResponse(new Response<>(MessageType.ERROR, false, "Internal Server Error", new ErrorDetail("INTERNAL_SERVER_ERROR", e.getMessage())));
        }
    }

    /**
     * Processes the request and returns a response.
     * @param request the request to handle
     * @return the response generated by the command
     */
    private Response<?> handleRequest(Request request) {
        User currentUser = SessionManager.getUser(clientChannel);

        // 1. Authentication Check
        if (request.getType() != MessageType.LOGIN && request.getType() != MessageType.SIGNUP && request.getType() != MessageType.PING) {
            if (currentUser == null) {
                return new Response<>(MessageType.ERROR, false, "Unauthorized: Please login first", null);
            }
        }

        // 2. Authorization Check (RBAC) - Centralized in Service
        if (!authService.canAccess(request.getType(), currentUser)) {
            return new Response<>(MessageType.ERROR, false, "Forbidden: User " + (currentUser != null ? currentUser.getAccountname() : "unknown") + " doesn't have permission for " + request.getType(), null);
        }

        // 3. Command Execution (SOLID: Command Pattern)
        Command command = commandRegistry.get(request.getType());
        if (command == null) {
            return new Response<>(MessageType.ERROR, false, "Unknown Command: " + request.getType(), null);
        }

        return command.execute(request, clientChannel);
    }

    /**
     * Sends a JSON-serialized response to the client.
     * @param response the response to send
     */
    private void sendResponse(Response<?> response) {
        synchronized (clientChannel) {
            if (!clientChannel.isOpen()) {
                FileLogger.warn("Cannot send response to " + clientAddress + ": Channel is closed.");
                return;
            }
            try {
                String json = JsonConverter.toJson(response);
                FileLogger.info("<<< OUTGOING to " + clientAddress + ": " + JsonConverter.maskSensitiveData(json));

                String messageWithNewline = json + "\n";
                ByteBuffer buffer = ByteBuffer.wrap(messageWithNewline.getBytes(StandardCharsets.UTF_8));
                while (buffer.hasRemaining()) {
                    int written = clientChannel.write(buffer);
                    if (written == 0) {
                        Thread.onSpinWait();
                    }
                }
            } catch (IOException e) {
                FileLogger.error("Failed to send response to " + clientAddress, e);
            }
        }
    }
}
