-- CREATE TABLE IF NOT EXISTS vets (
--   id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   first_name TEXT,
--   last_name  TEXT
-- );
-- CREATE INDEX ON vets (last_name);
--
-- CREATE TABLE IF NOT EXISTS specialties (
--   id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT
-- );
-- CREATE INDEX ON specialties (name);
--
-- CREATE TABLE IF NOT EXISTS vet_specialties (
--   vet_id       INT NOT NULL REFERENCES vets (id),
--   specialty_id INT NOT NULL REFERENCES specialties (id),
--   UNIQUE (vet_id, specialty_id)
-- );
--
-- CREATE TABLE IF NOT EXISTS types (
--   id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT
-- );
-- CREATE INDEX ON types (name);
--
-- CREATE TABLE IF NOT EXISTS owners (
--   id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   first_name TEXT,
--   last_name  TEXT,
--   address    TEXT,
--   city       TEXT,
--   telephone  TEXT
-- );
-- CREATE INDEX ON owners (last_name);
--
-- CREATE TABLE IF NOT EXISTS pets (
--   id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name       TEXT,
--   birth_date DATE,
--   type_id    INT NOT NULL REFERENCES types (id),
--   owner_id   INT REFERENCES owners (id)
-- );
-- CREATE INDEX ON pets (name);
-- CREATE INDEX ON pets (owner_id);
--
-- CREATE TABLE IF NOT EXISTS visits (
--   id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   pet_id      INT REFERENCES pets (id),
--   visit_date  DATE,
--   description TEXT
-- );
-- CREATE INDEX ON visits (pet_id);


-- 1. Tạo bảng users trước vì các bảng khác tham chiếu đến nó
CREATE TABLE users (
                       id VARCHAR(255) PRIMARY KEY,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       balance DECIMAL(15, 2) DEFAULT 0.00,
                       role VARCHAR(50),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tạo bảng products
CREATE TABLE products (
                          id SERIAL PRIMARY KEY,
                          product_name VARCHAR(255) NOT NULL,
                          description TEXT,
                          starting_price DECIMAL(15, 2) NOT NULL,
                          seller_id VARCHAR(255),
                          status VARCHAR(50),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Khóa ngoại liên kết với bảng users
                          CONSTRAINT fk_seller
                              FOREIGN KEY(seller_id)
                                  REFERENCES users(id)
                                  ON DELETE SET NULL
);

-- 3. Tạo bảng auctions (Bảng lưu lịch sử đấu giá)
CREATE TABLE auctions (
                          id SERIAL PRIMARY KEY,
                          product_id INTEGER NOT NULL,
                          bidder_id VARCHAR(255) NOT NULL,
                          bid_amount DECIMAL(15, 2) NOT NULL,
                          bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Khóa ngoại liên kết với bảng products
                          CONSTRAINT fk_product
                              FOREIGN KEY(product_id)
                                  REFERENCES products(id)
                                  ON DELETE CASCADE,

    -- Khóa ngoại liên kết với bảng users (người đấu giá)
                          CONSTRAINT fk_bidder
                              FOREIGN KEY(bidder_id)
                                  REFERENCES users(id)
                                  ON DELETE CASCADE
);
